name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run Unit Tests
      run: ./gradlew test
    
    - name: Run Android Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        script: ./gradlew connectedCheck
    
    - name: Generate JaCoCo Test Coverage Report
      run: ./gradlew jacocoTestReport
    
    - name: Upload Test Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: test-coverage-report
        path: app/build/reports/jacoco/
    
    - name: Generate Dokka Documentation
      run: ./gradlew dokkaHtml
    
    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: api-documentation
        path: app/build/dokka/
    
    - name: Build Release APK
      run: ./gradlew assembleRelease
    
    - name: Sign Release APK
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: |
        echo "${{ secrets.SIGNING_KEY_FILE }}" | base64 -d > keystore.jks
        ./gradlew signingReport
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          app/build/outputs/apk/release/app-release.apk
          app/build/reports/jacoco/jacocoTestReport.xml
          app/build/dokka/index.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update Changelog
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        ./gradlew updateChangelog
