name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup secrets
      env:
        GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
        GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > app/src/main/res/values/secrets.xml
        echo '<resources>' >> app/src/main/res/values/secrets.xml
        echo '    <string name="google_oauth_client_id">'$GOOGLE_OAUTH_CLIENT_ID'</string>' >> app/src/main/res/values/secrets.xml
        echo '    <string name="google_oauth_client_secret">'$GOOGLE_OAUTH_CLIENT_SECRET'</string>' >> app/src/main/res/values/secrets.xml
        echo '    <string name="maps_api_key">'$MAPS_API_KEY'</string>' >> app/src/main/res/values/secrets.xml
        echo '</resources>' >> app/src/main/res/values/secrets.xml

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run tests
      run: ./gradlew test

    - name: Generate test report
      run: ./gradlew jacocoTestReport

    - name: Generate documentation
      run: ./gradlew dokkaHtml

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Build release APK
      if: github.event_name == 'release'
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > keystore.jks.base64
        base64 -d keystore.jks.base64 > app/keystore/release.keystore
        ./gradlew assembleRelease

    - name: Upload APK
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
