name: Generate Documentation

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate documentation
        run: ./gradlew generateDocumentation

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: app/build/docs/

      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/build/docs
          branch: gh-pages
